server:
  port: 8001

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 15m
  refresh-token-expiration: 7d

logging:
  level:
    org.springframework.security: INFO
